### ISSUE TITLE
Create and link to the 'CoCo' 0.1.0 RC1 kata-containers payload in config/samples/ccruntime.yaml

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/operator#94]
Once we are happy that we've got all the outstanding kata-containers code merged into the `CCv0` branch, we need to re-generate the kata-containers payload from here (with the [doc](https://github.com/kata-containers/kata-containers/blob/CCv0/docs/how-to/how-to-generate-a-kata-containers-payload-for-the-confidential-containers-operator.md)) and update the version that the operator links to in `config/samples/ccruntime.yaml`

### Tasks

- [x] Generate the new payload
- [x] Create a PR to update the ccruntime to point to this
- [ ] Ensure that the operator CI tests are passing
- [ ] Publicise this update, so people can look at testing it.
